language: python
python:
  - 2.7
  - 3.3
install:
  - pip install -r dev-requirements.txt
  - pip install -e .
script:
  # Normal unit tests.
  - ./setup.py test
  # Code quality check.
  - pylint apyori.py test/*.py
notifications:
  - email: false
